sudo: required

language: go

go:
  - 1.6.3
  - 1.7.1
  - tip

services:
  - mysql

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('123456') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e "create database IF NOT EXISTS test;" -uroot -p123456
  - mysql -uroot -p123456 test < testfiles/test.sql
  - test -d $GOPATH/bin || mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

install:
  - make install

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
