Mode: TEST
ListenAddr: localhost
ListenPort: 8089
PubDir: testfiles
CertFile: certificate/localhost.cert
KeyFile: certificate/localhost.key
Db:
  SqlDriver: MySQL
  Protocol: tcp
  Hostname: localhost
  Username: root
  Password: 123456
  Dbname: test
  Charset: utf8
